name: CI – Build Docker Image

# 👇 When to run this workflow
on:
  push:
    branches: [main]    # run when you push to main branch
  pull_request:
    branches: [main]    # run when someone creates a PR to main

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub will create a Linux VM for you temporarily

    steps:
      # Step 1: Checkout the code from your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Java (JDK 17 for Spring Boot)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'       # Temurin is a reliable OpenJDK distro
          java-version: '17'

      # Step 3: Cache Maven dependencies for faster builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository         # Maven’s local repo
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      # Step 4: Build the Spring Boot JAR file
      - name: Build project with Maven
        run: ./mvnw clean package -DskipTests

      # Step 5: Build Docker image using Dockerfile in project root
      - name: Build Docker image
        run: docker build -t gamehub-backend:${{ github.sha }} .

