name: CI - Build GameHub Apps

on:
  push:
    branches:
      - main
    paths:
      - 'yatzee-api/**'
      - 'yatzee-frontend/**'
      - '.github/workflows/ci.yml'

jobs:
  backend:
    name: 🛠️ Build Backend
    if: github.event.head_commit.message != 'skip backend'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: yatzee-api

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: maven-${{ hashFiles('yatzee-api/pom.xml') }}
          restore-keys: |
            maven-

      - name: Build Docker image (backend)
        run: |
          docker build -t gamehub/yatzee-api:${{ github.sha }} .

      - name: Tag image with 'latest'
        run: docker tag gamehub/yatzee-api:${{ github.sha }} gamehub/yatzee-api:latest    
      
      - name: Log backend image size
        run: |
          size=$(docker image inspect gamehub/yatzee-api:${{ github.sha }} --format='{{.Size}}')
          echo "Backend Image Size: $size bytes (~$(($size / 1024 / 1024)) MB)"

      - name: Show Docker image layer sizes (Backend)
        run: docker history gamehub/yatzee-api:${{ github.sha }}

  frontend:
    name: 🌐 Build Frontend
    if: github.event.head_commit.message != 'skip frontend'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: yatzee-frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.cache
            yatzee-frontend/node_modules
          key: node-${{ hashFiles('yatzee-frontend/package-lock.json') }}
          restore-keys: |
            node-

      - name: Install dependencies
        run: npm ci

      - name: Build Frontend
        run: npm run build

      - name: Build Docker image (frontend)
        run: |
          docker build -t gamehub/yatzee-frontend:${{ github.sha }} .

      - name: Tag image with 'latest'
        run: docker tag gamehub/yatzee-frontend:${{ github.sha }} gamehub/yatzee-api:latest
      
      - name: Log backend image size
        run: |
          size=$(docker image inspect gamehub/yatzee-frontend:${{ github.sha }} --format='{{.Size}}')
          echo "Backend Image Size: $size bytes (~$(($size / 1024 / 1024)) MB)"

      - name: Show Docker image layer sizes (Backend)
        run: docker history gamehub/yatzee-frontend:${{ github.sha }}
